### ISSUE TITLE
StructuredHub.Publish(..., nil) creates an invalid pointer dereference panic

### ISSUE THREAD

**Issue by jameinel** [juju/pubsub#2]
I was playing around with some examples and I copied one of the SimpleHub tests and was using it for StructuredHub. Simple allows Publish(topic, nil), but if you do the same with Structured it gives:
(testing on Windows to make sure it was cross platform)
C:/Go/src/runtime/asm_amd64.s:472
  in call32
C:/Go/src/runtime/panic.go:443
  in gopanic
C:/Go/src/runtime/panic.go:62
  in panicmem
C:/Go/src/runtime/signal_windows.go:161
  in sigpanic
benchmark_test.go:107
  in BenchmarkSuite.BenchmarkStructuredPublishAndWaitOneSubscriber
C:/Go/src/runtime/asm_amd64.s:472
  in call32
C:/Go/src/reflect/value.go:435
  in Value.call
C:/Go/src/reflect/value.go:303
  in Value.Call
C:/Go/src/runtime/asm_amd64.s:1998
  in goexit
OOPS: 4 passed, 1 PANICKED

This was the setup and call:
func (*BenchmarkSuite) BenchmarkStructuredPublishAndWaitOneSubscriber(c *gc.C) {
    hub := pubsub.NewStructuredHub(nil)
    topic := pubsub.Topic("benchmarking")
    counter := 0
    sub, err := hub.Subscribe(topic, func(topic pubsub.Topic, s Emitter) {
        counter++
    })
    defer sub.Unsubscribe()
    c.Assert(err, jc.ErrorIsNil)
    failedCount := 0
    for i := 0; i < c.N; i++ {
        // Publishing nil results in a nil-pointer dereference
        result, err := hub.Publish(topic, nil)
        c.Assert(err, jc.ErrorIsNil)

```
    select {
    case <-result.Complete():
    case <-time.After(5 * veryShortTime):
        failedCount++
    }
}
```

**Comment by howbazaar** [comment]
Yep, that is a bug. It should be an error publish... or shoud it?

Perhaps publish nil should become map[string]interface{}{} ?

**Comment by howbazaar** [comment]
Added a benchmarks_test.go with your benchmark above.

$ go test -check.b
PASS: benchmarks_test.go:21: BenchmarkSuite.BenchmarkStructuredNoConversions      500000          3840 ns/op
OK: 1 passed
PASS
ok      github.com/juju/pubsub  1.976s
